# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas-docs.github.io/pandas-docs-travis/io.html#json
+ data source: http://jsonstudio.com/resources/
****

In [76]:
import pandas as pd
import numpy as np

## imports for Python, Pandas

In [2]:
import json
# This is the 'Pythonic' way 
# JSON: list of dictionaries
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas-docs.github.io/pandas-docs-travis/io.html#normalization

In [118]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [119]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [120]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population info.governor    state shortname
0        Dade       12345    Rick Scott  Florida        FL
1     Broward       40000    Rick Scott  Florida        FL
2  Palm Beach       60000    Rick Scott  Florida        FL
3      Summit        1234   John Kasich     Ohio        OH
4    Cuyahoga        1337   John Kasich     Ohio        OH

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [121]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{u'_id': {u'$oid': u'52b213b38594d8a2be17c780'},
  u'approvalfy': 1999,
  u'board_approval_month': u'November',
  u'boardapprovaldate': u'2013-11-12T00:00:00Z',
  u'borrower': u'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  u'closingdate': u'2018-07-07T00:00:00Z',
  u'country_namecode': u'Federal Democratic Republic of Ethiopia!$!ET',
  u'countrycode': u'ET',
  u'countryname': u'Federal Democratic Republic of Ethiopia',
  u'countryshortname': u'Ethiopia',
  u'docty': u'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  u'envassesmentcategorycode': u'C',
  u'grantamt': 0,
  u'ibrdcommamt': 0,
  u'id': u'P129828',
  u'idacommamt': 130000000,
  u'impagency': u'MINISTRY OF EDUCATION',
  u'lendinginstr': u'Investment Project Financing',
  u'lendinginstrtype': u'IN',
  u'lendprojectcost': 550000000,
  u'majorsector_percent': [{u'Name': u'Education', u'Percent': 46},
   {u'Name': u'Education', u'Percent': 26},
   {u'Name': u'Public Administration, Law, and Justice', u'Percent': 16},
   {u'Name': u'Education', u'Percent': 12}],
  u'mjsector_namecode': [{u'code': u'EX', u'name': u'Education'},
   {u'code': u'EX', u'name': u'Education'},
   {u'code': u'BX', u'name': u'Public Administration, Law, and Justice'},
   {u'code': u'EX', u'name': u'Education'}],
  u'mjtheme': [u'Human development'],
  u'mjtheme_namecode': [{u'code': u'8', u'name': u'Human development'},
   {u'code': u'11', u'name': u''}],
  u'mjthemecode': u'8,11',
  u'prodline': u'PE',
  u'prodlinetext': u'IBRD/IDA',
  u'productlinetype': u'L',
  u'project_abstract': {u'cdata': u'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  u'project_name': u'Ethiopia General Education Quality Improvement Project II',
  u'projectdocs': [{u'DocDate': u'28-AUG-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    u'EntityID': u'090224b081e545fb_1_0'},
   {u'DocDate': u'01-JUL-2013',
    u'DocType': u'IP',
    u'DocTypeDesc': u'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    u'EntityID': u'000442464_20130920111729'},
   {u'DocDate': u'22-NOV-2012',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    u'EntityID': u'090224b0817b19e2_1_0'}],
  u'projectfinancialtype': u'IDA',
  u'projectstatusdisplay': u'Active',
  u'regionname': u'Africa',
  u'sector': [{u'Name': u'Primary education'},
   {u'Name': u'Secondary education'},
   {u'Name': u'Public administration- Other social services'},
   {u'Name': u'Tertiary education'}],
  u'sector1': {u'Name': u'Primary education', u'Percent': 46},
  u'sector2': {u'Name': u'Secondary education', u'Percent': 26},
  u'sector3': {u'Name': u'Public administration- Other social services',
   u'Percent': 16},
  u'sector4': {u'Name': u'Tertiary education', u'Percent': 12},
  u'sector_namecode': [{u'code': u'EP', u'name': u'Primary education'},
   {u'code': u'ES', u'name': u'Secondary education'},
   {u'code': u'BS', u'name': u'Public administration- Other social services'},
   {u'code': u'ET', u'name': u'Tertiary education'}],
  u'sectorcode': u'ET,BS,ES,EP',
  u'source': u'IBRD',
  u'status': u'Active',
  u'supplementprojectflg': u'N',
  u'theme1': {u'Name': u'Education for all', u'Percent': 100},
  u'theme_namecode': [{u'code': u'65', u'name': u'Education for all'}],
  u'themecode': u'65',
  u'totalamt': 130000000,
  u'totalcommamt': 130000000,
  u'url': u'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {u'_id': {u'$oid': u'52b213b38594d8a2be17c781'},
  u'approvalfy': 2015,
  u'board_approval_month': u'November',
  u'boardapprovaldate': u'2013-11-04T00:00:00Z',
  u'borrower': u'GOVERNMENT OF TUNISIA',
  u'country_namecode': u'Republic of Tunisia!$!TN',
  u'countrycode': u'TN',
  u'countryname': u'Republic of Tunisia',
  u'countryshortname': u'Tunisia',
  u'docty': u'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  u'envassesmentcategorycode': u'C',
  u'grantamt': 4700000,
  u'ibrdcommamt': 0,
  u'id': u'P144674',
  u'idacommamt': 0,
  u'impagency': u'MINISTRY OF FINANCE',
  u'lendinginstr': u'Specific Investment Loan',
  u'lendinginstrtype': u'IN',
  u'lendprojectcost': 5700000,
  u'majorsector_percent': [{u'Name': u'Public Administration, Law, and Justice',
    u'Percent': 70},
   {u'Name': u'Public Administration, Law, and Justice', u'Percent': 30}],
  u'mjsector_namecode': [{u'code': u'BX',
    u'name': u'Public Administration, Law, and Justice'},
   {u'code': u'BX', u'name': u'Public Administration, Law, and Justice'}],
  u'mjtheme': [u'Economic management',
   u'Social protection and risk management'],
  u'mjtheme_namecode': [{u'code': u'1', u'name': u'Economic management'},
   {u'code': u'6', u'name': u'Social protection and risk management'}],
  u'mjthemecode': u'1,6',
  u'prodline': u'RE',
  u'prodlinetext': u'Recipient Executed Activities',
  u'productlinetype': u'L',
  u'project_name': u'TN: DTF Social Protection Reforms Support',
  u'projectdocs': [{u'DocDate': u'29-MAR-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    u'EntityID': u'000333037_20131024115616'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    u'EntityID': u'000356161_20131024151611'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    u'EntityID': u'000442464_20131031112136'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    u'EntityID': u'000333037_20131031105716'},
   {u'DocDate': u'16-JAN-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    u'EntityID': u'000356161_20130305113209'},
   {u'DocDate': u'16-JAN-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    u'EntityID': u'000356161_20130305113716'}],
  u'projectfinancialtype': u'OTHER',
  u'projectstatusdisplay': u'Active',
  u'regionname': u'Middle East and North Africa',
  u'sector': [{u'Name': u'Public administration- Other social services'},
   {u'Name': u'General public administration sector'}],
  u'sector1': {u'Name': u'Public administration- Other social services',
   u'Percent': 70},
  u'sector2': {u'Name': u'General public administration sector',
   u'Percent': 30},
  u'sector_namecode': [{u'code': u'BS',
    u'name': u'Public administration- Other social services'},
   {u'code': u'BZ', u'name': u'General public administration sector'}],
  u'sectorcode': u'BZ,BS',
  u'source': u'IBRD',
  u'status': u'Active',
  u'supplementprojectflg': u'N',
  u'theme1': {u'Name': u'Other economic management', u'Percent': 30},
  u'theme_namecode': [{u'code': u'24', u'name': u'Other economic management'},
   {u'code': u'54', u'name': u'Social safety nets'}],
  u'themecode': u'54,24',
  u'totalamt': 0,
  u'totalcommamt': 4700000,
  u'url': u'http://www.worldbank.org/projects/P144674?lang=en'}]

In [122]:
# load as Pandas dataframe
# Note that Pandas assumes that the JSON file is well-structured
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{u'$oid': u'52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{u'Percent': 100, u'Name': u'Education for all'}","[{u'code': u'65', u'name': u'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{u'$oid': u'52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Other economic man...","[{u'code': u'24', u'name': u'Other economic ma...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [123]:
json_df = pd.read_json('data/world_bank_projects.json')

In [124]:
json_df.head(5)

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{u'$oid': u'52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{u'Percent': 100, u'Name': u'Education for all'}","[{u'code': u'65', u'name': u'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{u'$oid': u'52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Other economic man...","[{u'code': u'24', u'name': u'Other economic ma...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{u'$oid': u'52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{u'Percent': 46, u'Name': u'Regional integrati...","[{u'code': u'47', u'name': u'Regional integrat...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{u'$oid': u'52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{u'Percent': 50, u'Name': u'Participation and ...","[{u'code': u'57', u'name': u'Participation and...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{u'$oid': u'52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Export development...","[{u'code': u'45', u'name': u'Export developmen...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [125]:
json_df.columns

Index([                     u'_id',               u'approvalfy',
           u'board_approval_month',        u'boardapprovaldate',
                       u'borrower',              u'closingdate',
               u'country_namecode',              u'countrycode',
                    u'countryname',         u'countryshortname',
                          u'docty', u'envassesmentcategorycode',
                       u'grantamt',              u'ibrdcommamt',
                             u'id',               u'idacommamt',
                      u'impagency',             u'lendinginstr',
               u'lendinginstrtype',          u'lendprojectcost',
            u'majorsector_percent',        u'mjsector_namecode',
                        u'mjtheme',         u'mjtheme_namecode',
                    u'mjthemecode',                 u'prodline',
                   u'prodlinetext',          u'productlinetype',
               u'project_abstract',             u'project_name',
                    u'projectdocs',     u'projectfinancialtype',
           u'projectstatusdisplay',               u'regionname',
                         u'sector',                  u'sector1',
                        u'sector2',                  u'sector3',
                        u'sector4',          u'sector_namecode',
                     u'sectorcode',                   u'source',
                         u'status',     u'supplementprojectflg',
                         u'theme1',           u'theme_namecode',
                      u'themecode',                 u'totalamt',
                   u'totalcommamt',                      u'url'],
      dtype='object')

# Excercise 1

In [175]:
json_df.groupby(['countryname']).size().order(ascending=False).head(10)

countryname
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Nepal                              12
People's Republic of Bangladesh    12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
dtype: int64

In [176]:
# Alternative solution, with help from Alex
json_df['countryname'].value_counts()[0:10]

People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Kingdom of Morocco                 12
People's Republic of Bangladesh    12
Nepal                              12
Republic of Mozambique             11
Africa                             11
dtype: int64

# Excercise 2: Find the top 10 major project themes (using column 'mjtheme_namecode')

In [177]:
# First attempt: same as above:
json_df['mjtheme_namecode'].value_counts()[0:10]

[{u'code': u'11', u'name': u'Environment and natural resources management'}, {u'code': u'11', u'name': u'Environment and natural resources management'}]                                                                                            12
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'11', u'name': u''}]                                                                                                                                                                    11
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}]                                                                                                                                                     8
[{u'code': u'4', u'name': u'Financial and private sector development'}, {u'code': u'4', u'name': u'Financial and private sector development'}]                                                                                                       6
[{u'code': u'2', u'name': u'Public sector governance'}, {u'code': u'2', u'name': u'Public sector governance'}, {u'code': u'2', u'name': u'Public sector governance'}]                                                                                6
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'7', u'name': u'Social dev/gender/inclusion'}]                                                                                                                                           5
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}]     5
[{u'code': u'11', u'name': u'Environment and natural resources management'}, {u'code': u'11', u'name': u''}]                                                                                                                                         5
[{u'code': u'11', u'name': u'Environment and natural resources management'}, {u'code': u'4', u'name': u''}]                                                                                                                                          5
[{u'code': u'4', u'name': u'Financial and private sector development'}, {u'code': u'5', u'name': u'Trade and integration'}]                                                                                                                          5
dtype: int64

In [178]:
# OK, so this gives a dictionary... let's try the normalize first
json_raw=json.load(open('data/world_bank_projects.json'))
#json_normalize(json_raw, 'mjtheme_namecode')

In [179]:
json_norm = json_normalize(json_raw, 'mjtheme_namecode')
json_norm

     code                                          name
0       8                             Human development
1      11
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8
18     10                             Rural development
19      7
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5
1482    6         Social protection and risk management
1483    8
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [180]:
json_norm['name'].value_counts()[:10]

Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
dtype: int64

# Excercise 3: In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [181]:
# Unfortunately, isnull applied to an empty dictionary gives back a false, so I need a lambda function...
f=lambda x: len(str(x)) > 0
json_filter=json_norm['name'].map(f)

In [182]:
# Let's look at what element 1 looks like
json_filtered=json_norm[json_filter]

In [183]:
json_filtered

     code                                          name
0       8                             Human development
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
18     10                             Rural development
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
30      5                         Trade and integration
31     11  Environment and natural resources management
32     10                             Rural development
33      6         Social protection and risk management
34      6         Social protection and risk management
35      6         Social protection and risk management
...   ...                                           ...
1465   11  Environment and natural resources management
1466    8                             Human development
1467    2                      Public sector governance
1468    2                      Public sector governance
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1482    6         Social protection and risk management
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1377 rows x 2 columns]

In [184]:
json_filtered=json_filtered.groupby(['code', 'name']).size()

In [185]:
json_filtered

code  name
1     Economic management                              33
10    Rural development                               202
11    Environment and natural resources management    223
2     Public sector governance                        184
3     Rule of law                                      12
4     Financial and private sector development        130
5     Trade and integration                            72
6     Social protection and risk management           158
7     Social dev/gender/inclusion                     119
8     Human development                               197
9     Urban development                                47
dtype: int64

In [187]:
json_filtered['1']

name
Economic management    33
dtype: int64

In [205]:
df= pd.DataFrame(json_filtered)
df

                                                     0
code name
1    Economic management                            33
10   Rural development                             202
11   Environment and natural resources management  223
2    Public sector governance                      184
3    Rule of law                                    12
4    Financial and private sector development      130
5    Trade and integration                          72
6    Social protection and risk management         158
7    Social dev/gender/inclusion                   119
8    Human development                             197
9    Urban development                              47

In [206]:
df=df.reset_index(['name'])
#df.drop(['0'], axis=1, inplace=True)

In [207]:
df

                                              name    0
code
1                              Economic management   33
10                               Rural development  202
11    Environment and natural resources management  223
2                         Public sector governance  184
3                                      Rule of law   12
4         Financial and private sector development  130
5                            Trade and integration   72
6            Social protection and risk management  158
7                      Social dev/gender/inclusion  119
8                                Human development  197
9                                Urban development   47

In [208]:
df.drop([0], axis=1, inplace=True)

In [209]:
df

                                              name
code
1                              Economic management
10                               Rural development
11    Environment and natural resources management
2                         Public sector governance
3                                      Rule of law
4         Financial and private sector development
5                            Trade and integration
6            Social protection and risk management
7                      Social dev/gender/inclusion
8                                Human development
9                                Urban development

In [214]:
type(json_norm)

pandas.core.frame.DataFrame

In [223]:
json_norm=json_norm.merge(df.reset_index(['code']), on='code', how='left')

In [226]:
json_norm=json_norm.drop('name_x', axis=1)

In [228]:
json_norm.rename(columns={'name_y': 'name'}, inplace=True)

In [229]:
json_norm

     code                                          name
0       8                             Human development
1      11  Environment and natural resources management
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                             Human development
18     10                             Rural development
19      7                   Social dev/gender/inclusion
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                      Public sector governance
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4      Financial and private sector development
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11  Environment and natural resources management
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                         Trade and integration
1482    6         Social protection and risk management
1483    8                             Human development
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6         Social protection and risk management
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [137]:
# OK, so that worked...

In [116]:
json_filled=json_norm.replace(json_filtered)
json_filled

     code                                          name
0       8                             Human development
1      11                                           NaN
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6                                           NaN
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                                           NaN
18     10                             Rural development
19      7                                           NaN
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                                           NaN
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4                                           NaN
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11                                           NaN
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                                           NaN
1482    6         Social protection and risk management
1483    8                                           NaN
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6                                           NaN
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

# Earlier attempts (appendix kept)

In [32]:
n=len(json_df["_id"])
for i in range(n):
    temp = json_df["_id"][i]["$oid"]
    json_df["_id"][i] = temp

C:\Users\m01i795\AppData\Local\Continuum\Anaconda\lib\site-packages\IPython\kernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [48]:
json_df.columns

Index([                     u'_id',               u'approvalfy',
           u'board_approval_month',        u'boardapprovaldate',
                       u'borrower',              u'closingdate',
               u'country_namecode',              u'countrycode',
                    u'countryname',         u'countryshortname',
                          u'docty', u'envassesmentcategorycode',
                       u'grantamt',              u'ibrdcommamt',
                             u'id',               u'idacommamt',
                      u'impagency',             u'lendinginstr',
               u'lendinginstrtype',          u'lendprojectcost',
            u'majorsector_percent',        u'mjsector_namecode',
                        u'mjtheme',         u'mjtheme_namecode',
                    u'mjthemecode',                 u'prodline',
                   u'prodlinetext',          u'productlinetype',
               u'project_abstract',             u'project_name',
                    u'projectdocs',     u'projectfinancialtype',
           u'projectstatusdisplay',               u'regionname',
                         u'sector',                  u'sector1',
                        u'sector2',                  u'sector3',
                        u'sector4',          u'sector_namecode',
                     u'sectorcode',                   u'source',
                         u'status',     u'supplementprojectflg',
                         u'theme1',           u'theme_namecode',
                      u'themecode',                 u'totalamt',
                   u'totalcommamt',                      u'url'],
      dtype='object')

In [49]:
json_df['mjtheme_namecode'].value_counts()[0:10]

[{u'code': u'11', u'name': u'Environment and natural resources management'}, {u'code': u'11', u'name': u'Environment and natural resources management'}]                                                                                            12
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'11', u'name': u''}]                                                                                                                                                                    11
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}]                                                                                                                                                     8
[{u'code': u'4', u'name': u'Financial and private sector development'}, {u'code': u'4', u'name': u'Financial and private sector development'}]                                                                                                       6
[{u'code': u'2', u'name': u'Public sector governance'}, {u'code': u'2', u'name': u'Public sector governance'}, {u'code': u'2', u'name': u'Public sector governance'}]                                                                                6
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'7', u'name': u'Social dev/gender/inclusion'}]                                                                                                                                           5
[{u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}, {u'code': u'8', u'name': u'Human development'}]     5
[{u'code': u'11', u'name': u'Environment and natural resources management'}, {u'code': u'11', u'name': u''}]                                                                                                                                         5
[{u'code': u'11', u'name': u'Environment and natural resources management'}, {u'code': u'4', u'name': u''}]                                                                                                                                          5
[{u'code': u'4', u'name': u'Financial and private sector development'}, {u'code': u'5', u'name': u'Trade and integration'}]                                                                                                                          5
dtype: int64

In [ ]:
# So I need to unpack the value, or do the normalization

In [43]:
json_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 0 to 499
Data columns (total 50 columns):
_id                         500 non-null object
approvalfy                  500 non-null int64
board_approval_month        500 non-null object
boardapprovaldate           500 non-null object
borrower                    485 non-null object
closingdate                 370 non-null object
country_namecode            500 non-null object
countrycode                 500 non-null object
countryname                 500 non-null object
countryshortname            500 non-null object
docty                       446 non-null object
envassesmentcategorycode    430 non-null object
grantamt                    500 non-null int64
ibrdcommamt                 500 non-null int64
id                          500 non-null object
idacommamt                  500 non-null int64
impagency                   472 non-null object
lendinginstr                495 non-null object
lendinginstrtype            495 non-null object
lendprojectcost             500 non-null int64
majorsector_percent         500 non-null object
mjsector_namecode           500 non-null object
mjtheme                     491 non-null object
mjtheme_namecode            500 non-null object
mjthemecode                 500 non-null object
prodline                    500 non-null object
prodlinetext                500 non-null object
productlinetype             500 non-null object
project_abstract            362 non-null object
project_name                500 non-null object
projectdocs                 446 non-null object
projectfinancialtype        500 non-null object
projectstatusdisplay        500 non-null object
regionname                  500 non-null object
sector                      500 non-null object
sector1                     500 non-null object
sector2                     380 non-null object
sector3                     265 non-null object
sector4                     174 non-null object
sector_namecode             500 non-null object
sectorcode                  500 non-null object
source                      500 non-null object
status                      500 non-null object
supplementprojectflg        498 non-null object
theme1                      500 non-null object
theme_namecode              491 non-null object
themecode                   491 non-null object
totalamt                    500 non-null int64
totalcommamt                500 non-null int64
url                         500 non-null object
dtypes: int64(7), object(43)
memory usage: 199.2+ KB

In [44]:
json_df.isnull()
# categorical, consider mode
# string: replace with ""
# numeric: median (or mean)

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
13,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
471,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
472,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
473,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
474,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
475,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
476,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
477,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
478,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
479,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
480,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
481,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
482,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
483,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
484,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
485,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
486,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
487,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
488,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
489,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
490,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
491,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
492,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
493,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
494,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False